### PR TITLE
update data for 2020-03

### PR DESCRIPTION
**Pull request by maxheld83**

### CODE REVIEW

**Comment by maxheld83** [comment]
thanks for the refactoring @jhoeffler!

Just a warning: This branch has diverged pretty widely from `master` by now, and it would be best to only add new work off of `master`, because otherwise this will just be duplicate work for whoever is merging this branch (hehe, that'd be me 🙂 I guess).

**Comment by maxheld83** [comment]
waiting for some more changes from @jhoeffler before merging this.

**Comment by njahn82** [comment]
I would prefer to have these changes in a separate branch.

**Comment by maxheld83** [comment]
alright, I'm going to merge this as of https://github.com/subugoe/hoad/pull/172/commits/344d262769887bc8b226be92c4636c1c566f6172 then, which would be without @jhoeffler's commits. 

We can then take those to a separate branch.

**Comment by maxheld83** [comment]
@jhoeffler I'm going to revert your two last commits on this branch, just to have a clean merge of this long-standing PR. 
But your work can still be found over at #212.

**Pull request merged**
